# query UserWhereUnique($where: ProjectWhereUniqueInput!, $first: Int = 10) {
# 	user(where: $where, stage: $stage, locale: $locale) {
# 		...UserFields

# 		screenShots(first: $first) {
# 			...ImageFields
# 		}
# 	}
# }



# query ProjectWhereUniqueId(
# 	$where: ProjectWhereUniqueInput! = { id: "clhxnw5chfpxm0bk7zwvofkdw" }
# 	$stage: Stage = PUBLISHED
# ) {
# 	project(where: $where, stage: $stage) {
# 		id
# 		title
# 		link
# 		description
# 		version
# 		active
# 		sourceCode
# 		techStack
# 		createdAt
# 		updatedAt
# 		stage
# 		locale

# 		screenShots pages/lib

# 			id
# 			url
# 			handle
# 			fileName
# 			mimeType
# 			width
# 			height
# 			size
# 			createdAt
# 			updatedAt
# 			stage
# 			locale
# 		}
# 	}
# }

# # query ProjectById($id: ID!) {
# # 	project(where: { id: $id }) {
# # 		id
# # 		title
# # 		description
# # 		active
# # 		link
# # 		version
# # 		sourceCode
# # 		techStack
# # 		createdAt
# # 		updatedAt
# # 		stage
# # 		locale

# # 		screenShots {
# # 			id
# # 			url
# # 			handle
# # 			fileName
# # 			mimeType
# # 			width
# # 			height
# # 			size
# # 			createdAt
# # 			updatedAt
# # 			stage
# # 			locale
# # 		}
# # 	}
# # }

# # query ProjectsWhereActiveStage(
# # 	$where: ProjectInput = { active: true }
# # 	$stage: Stage = DRAFT
# # ) {
# # 	projectsConnection(where: $where, stage: $stage) {
# # 		edges {
# # 			node {
# # 				...ProjectFields

# # 				screenShots(first: 10) {
# # 					history(limit: 10) {
# # 						...ImageFields
# # 					}
# # 				}
# # 			}
# # 		}
# # 	}
# # }

# # query AllUsers {
# # 	users {
# # 		...UserFields
# # 	}
# # }

# # query UserById($where: UserInput = { "id": "cl2jewzic0nfr01xl28no3fa0"}, $locale: Locale = "en_US") {
# #   user(where: $where, locale: $locale) {
# # 	...UserFields
# #   }
# # }

# # query UsersWhereActiveNameContains(
# # 	$where: UserInput = { isActive: true, kind: MEMBER, name_contains: "bran" }
# # 	$orderBy: Order = "name_DESC"
# # 	$stage: Stage = DRAFT
# # ) {
# # 	usersConnection(where: $where, orderBy: $orderBy, stage: $stage) {
# # 		edges {
# # 			node {
# # 				id
# # 				name
# # 				kind
# # 				isActive
# # 				picture
# # 				createdAt
# # 				updatedAt
# # 				stage
# # 			}
# # 		}
# # 	}
# # }

# query UserWhereUnique($where: UserWhereUniqueInput!) {
# 	user(where: $where) {
# 		...UserFields
# 	}
# }
