fragment UserFields on User {
	id
	name
	kind
	isActive
	picture
	stage
	createdAt
	updatedAt
}

fragment ProjectFields on Project {
	id
	title
	description
	active
	link
	version
	sourceCode
	techStack
	createdAt
	updatedAt
	locale
}

fragment ImageFields on Asset {
	id
	url
	handle
	fileName
	mimeType
	width
	height
	size
}
