query UsersWhereActiveNameContains(
	$where: UserWhereInput = { isActive: true, kind: MEMBER, name_contains: "bran" }
	$orderBy: String = "name_DESC"
	$stage: Stage = DRAFT
) {
	usersConnection(where: $where, orderBy: $orderBy, stage: $stage) {
		edges {
			node {
				id
				name
				kind
				isActive
				picture
				createdAt
				updatedAt
				stage
			}
		}
	}
}
