query AllProjects {
  projects {
    title
    description
    activeTypedDocumentNode
    version
    createdAt
    updatedAt
    screenShots {
      fileName
      id
      mimeType
      url
    }
  }
}`
